2021-12-01 12:21:41.082 [main] INFO  org.example.App - New trainer was added
2021-12-01 12:21:41.119 [main] INFO  org.example.App - {"id":1638350500980,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 12:21:40","actor":"system","methodName":"createNewTrainer","status":"SUCCESS"}
2021-12-01 12:21:41.442 [main] INFO  org.example.App - Connected to db
2021-12-01 12:21:41.529 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 12:21:41.532 [main] INFO  org.example.App - Collection received
2021-12-01 12:21:41.568 [main] INFO  org.example.App - Record added
2021-12-01 12:33:09.884 [main] INFO  org.example.App - New trainer was added
2021-12-01 12:33:09.916 [main] INFO  org.example.App - {"id":1638351189810,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 12:33:09","actor":"system","methodName":"createNewTrainer","status":"SUCCESS"}
2021-12-01 12:33:10.184 [main] INFO  org.example.App - Connected to db
2021-12-01 12:33:10.228 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 12:33:10.231 [main] INFO  org.example.App - Collection received
2021-12-01 12:33:10.249 [main] INFO  org.example.App - Record added
2021-12-01 12:37:03.244 [main] INFO  org.example.App - New trainer was added
2021-12-01 12:37:03.275 [main] INFO  org.example.App - {"id":1638351423157,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 12:37:03","actor":"system","methodName":"createNewTrainer","status":"SUCCESS"}
2021-12-01 12:37:03.551 [main] INFO  org.example.App - Connected to db
2021-12-01 12:37:03.605 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 12:37:03.611 [main] INFO  org.example.App - Collection received
2021-12-01 12:37:03.631 [main] INFO  org.example.App - Record added
2021-12-01 12:37:52.882 [main] INFO  org.example.App - New trainer was added
2021-12-01 12:37:52.909 [main] INFO  org.example.App - {"id":1638351472797,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 12:37:52","actor":"system","methodName":"createNewTrainer","status":"SUCCESS"}
2021-12-01 12:37:53.125 [main] INFO  org.example.App - Connected to db
2021-12-01 12:37:53.163 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 12:37:53.166 [main] INFO  org.example.App - Collection received
2021-12-01 12:37:53.181 [main] INFO  org.example.App - Record added
2021-12-01 12:37:58.925 [main] INFO  org.example.App - Records were selected
2021-12-01 12:40:44.810 [main] INFO  org.example.App - Records were selected
2021-12-01 12:42:59.280 [main] INFO  org.example.App - New trainer was added
2021-12-01 12:42:59.313 [main] INFO  org.example.App - {"id":1638351779200,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 12:42:59","actor":"system","methodName":"createNewTrainer","status":"SUCCESS"}
2021-12-01 12:42:59.544 [main] INFO  org.example.App - Connected to db
2021-12-01 12:42:59.587 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 12:42:59.590 [main] INFO  org.example.App - Collection received
2021-12-01 12:42:59.607 [main] INFO  org.example.App - Record added
2021-12-01 12:43:13.838 [main] INFO  org.example.App - Records were selected
2021-12-01 12:44:31.574 [main] INFO  org.example.App - Records were selected
2021-12-01 12:45:40.420 [main] INFO  org.example.App - Records were selected
2021-12-01 12:49:57.497 [main] INFO  org.example.App - Possible
2021-12-01 12:49:57.589 [main] INFO  org.example.App - Records were selected
2021-12-01 12:50:27.389 [main] INFO  org.example.App - All records were added
2021-12-01 12:50:27.419 [main] INFO  org.example.App - {"id":1638352227303,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 12:50:27","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-01 12:50:27.643 [main] INFO  org.example.App - Connected to db
2021-12-01 12:50:27.680 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 12:50:27.683 [main] INFO  org.example.App - Collection received
2021-12-01 12:50:27.697 [main] INFO  org.example.App - Record added
2021-12-01 12:50:33.089 [main] INFO  org.example.App - Possible
2021-12-01 12:50:33.159 [main] INFO  org.example.App - Records were selected
2021-12-01 13:15:09.453 [main] INFO  org.example.App - Possible
2021-12-01 13:15:09.542 [main] INFO  org.example.App - Records were selected
2021-12-01 13:15:09.543 [main] INFO  org.example.App - Possible
2021-12-01 13:15:09.551 [main] INFO  org.example.App - Records were selected
2021-12-01 13:15:09.552 [main] INFO  org.example.App - Trainer was found
2021-12-01 13:15:09.580 [main] INFO  org.example.App - {"id":1638353709544,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 13:15:09","actor":"system","methodName":"getTrainerById","status":"SUCCESS"}
2021-12-01 13:15:09.805 [main] INFO  org.example.App - Connected to db
2021-12-01 13:15:09.848 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 13:15:09.851 [main] INFO  org.example.App - Collection received
2021-12-01 13:15:09.871 [main] INFO  org.example.App - Record added
2021-12-01 13:16:30.864 [main] INFO  org.example.App - Possible
2021-12-01 13:16:30.953 [main] INFO  org.example.App - Records were selected
2021-12-01 13:16:30.954 [main] INFO  org.example.App - Possible
2021-12-01 13:16:30.961 [main] INFO  org.example.App - Records were selected
2021-12-01 13:16:30.962 [main] INFO  org.example.App - Trainer was found
2021-12-01 13:16:30.991 [main] INFO  org.example.App - {"id":1638353790954,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 13:16:30","actor":"system","methodName":"getTrainerById","status":"SUCCESS"}
2021-12-01 13:16:31.197 [main] INFO  org.example.App - Connected to db
2021-12-01 13:16:31.247 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 13:16:31.251 [main] INFO  org.example.App - Collection received
2021-12-01 13:16:31.268 [main] INFO  org.example.App - Record added
2021-12-01 13:21:27.219 [main] INFO  org.example.App - Possible
2021-12-01 13:21:27.309 [main] INFO  org.example.App - Records were selected
2021-12-01 13:21:27.311 [main] ERROR org.example.App - org.example.Exceptions.NullObjectExceptionBean not found
2021-12-01 13:21:27.337 [main] INFO  org.example.App - {"id":1638354087211,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 13:21:27","actor":"system","methodName":"getTrainerById","status":"FAULT"}
2021-12-01 13:21:27.547 [main] INFO  org.example.App - Connected to db
2021-12-01 13:21:27.588 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 13:21:27.591 [main] INFO  org.example.App - Collection received
2021-12-01 13:21:27.607 [main] INFO  org.example.App - Record added
2021-12-01 13:22:31.749 [main] INFO  org.example.App - Possible
2021-12-01 13:22:31.832 [main] INFO  org.example.App - Records were selected
2021-12-01 13:22:31.833 [main] INFO  org.example.App - Possible
2021-12-01 13:22:31.842 [main] INFO  org.example.App - Records were selected
2021-12-01 13:22:31.843 [main] INFO  org.example.App - Trainer was found
2021-12-01 13:22:31.872 [main] INFO  org.example.App - {"id":1638354151833,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 13:22:31","actor":"system","methodName":"getTrainerById","status":"SUCCESS"}
2021-12-01 13:22:32.089 [main] INFO  org.example.App - Connected to db
2021-12-01 13:22:32.129 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 13:22:32.133 [main] INFO  org.example.App - Collection received
2021-12-01 13:22:32.148 [main] INFO  org.example.App - Record added
2021-12-01 13:22:32.148 [main] INFO  org.example.App - Possible
2021-12-01 13:22:32.159 [main] INFO  org.example.App - Records were selected
2021-12-01 13:22:32.159 [main] INFO  org.example.App - Trainer was found
2021-12-01 13:22:32.160 [main] INFO  org.example.App - {"id":1638354151833,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 13:22:31","actor":"system","methodName":"getTrainerById","status":"SUCCESS"}
2021-12-01 13:22:32.162 [main] INFO  org.example.App - Connected to db
2021-12-01 13:22:32.169 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 13:22:32.170 [main] INFO  org.example.App - Collection received
2021-12-01 13:22:32.171 [main] INFO  org.example.App - Record added
2021-12-01 13:22:32.171 [main] INFO  org.example.App - Possible
2021-12-01 13:22:32.176 [main] INFO  org.example.App - Records were selected
2021-12-01 13:22:32.177 [main] INFO  org.example.App - {"id":1638354151833,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 13:22:31","actor":"system","methodName":"getTrainerById","status":"SUCCESS"}
2021-12-01 13:22:32.180 [main] INFO  org.example.App - Connected to db
2021-12-01 13:22:32.222 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 13:22:32.222 [main] INFO  org.example.App - Collection received
2021-12-01 13:22:32.224 [main] INFO  org.example.App - Record added
2021-12-01 13:22:32.224 [main] INFO  org.example.App - Trainer was deleted
2021-12-01 13:22:32.235 [main] INFO  org.example.App - All records were added
2021-12-01 13:22:32.235 [main] INFO  org.example.App - {"id":1638354151833,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 13:22:31","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-01 13:22:32.237 [main] INFO  org.example.App - Connected to db
2021-12-01 13:22:32.245 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 13:22:32.245 [main] INFO  org.example.App - Collection received
2021-12-01 13:22:32.246 [main] INFO  org.example.App - Record added
2021-12-01 13:22:32.247 [main] INFO  org.example.App - {"id":1638354151833,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 13:22:31","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-01 13:22:32.250 [main] INFO  org.example.App - Connected to db
2021-12-01 13:22:32.258 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 13:22:32.258 [main] INFO  org.example.App - Collection received
2021-12-01 13:22:32.259 [main] INFO  org.example.App - Record added
2021-12-01 13:22:32.259 [main] INFO  org.example.App - Trainer was updated
2021-12-01 13:22:32.262 [main] INFO  org.example.App - New trainer was added
2021-12-01 13:22:32.263 [main] INFO  org.example.App - {"id":1638354151833,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 13:22:31","actor":"system","methodName":"createNewTrainer","status":"SUCCESS"}
2021-12-01 13:22:32.265 [main] INFO  org.example.App - Connected to db
2021-12-01 13:22:32.276 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 13:22:32.276 [main] INFO  org.example.App - Collection received
2021-12-01 13:22:32.277 [main] INFO  org.example.App - Record added
2021-12-01 13:22:32.277 [main] INFO  org.example.App - Possible
2021-12-01 13:22:32.282 [main] INFO  org.example.App - Records were selected
2021-12-01 13:22:32.282 [main] INFO  org.example.App - Trainer was found
2021-12-01 13:22:32.283 [main] INFO  org.example.App - {"id":1638354152279,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"01/12/2021 13:22:32","actor":"system","methodName":"getTrainerById","status":"SUCCESS"}
2021-12-01 13:22:32.284 [main] INFO  org.example.App - Connected to db
2021-12-01 13:22:32.292 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-01 13:22:32.293 [main] INFO  org.example.App - Collection received
2021-12-01 13:22:32.294 [main] INFO  org.example.App - Record added
